# Generated by Django 3.0 on 2022-05-07 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220409_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='resume'),
            preserve_default=False,
        ),
    ]
