# Generated by Django 3.0 on 2022-05-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220507_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.CharField(max_length=500),
        ),
    ]
