# Generated by Django 3.0 on 2022-05-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220507_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
