# Generated by Django 3.0 on 2022-05-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user_email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
